#!/bin/bash
# Files created that need to be added to Xcode project:
echo "New files to add to Xcode:"
echo "1. Viewpoint/Models/IndigoModels.swift"
echo "2. Viewpoint/Views/IndigoView.swift"
echo "3. Viewpoint/Views/VisualEffectView.swift"
echo "4. Viewpoint/ViewModels/IndigoViewModel.swift"
echo "5. Viewpoint/Services/AudioRecorder.swift"
echo "6. Viewpoint/Services/WhisperService.swift"
echo ""
echo "In Xcode:"
echo "1. Right-click on the 'Viewpoint' group in the Project Navigator"
echo "2. Select 'Add Files to Viewpoint...'"
echo "3. Navigate to each folder and select the new files"
echo "4. Make sure 'Copy items if needed' is UNCHECKED"
echo "5. Make sure 'Viewpoint' target is CHECKED"
echo "6. Click Add"
echo ""
echo "Or drag and drop these files from Finder into their respective groups in Xcode."
